kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: garu-io-frontend-api
  namespace: garu-io-frontend-api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #nginx.ingress.kubernetes.io/cors-allow-origin: "https://garu.io"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:

    - host: api.garu.io
      http:
        paths:
          - path: /portfolio/(.+)
            backend:
              serviceName: garu-io-frontend-api
              servicePort: 80
          - path: /personal/(.+)
            backend:
              serviceName: garu-io-frontend-api
              servicePort: 80

  tls:
    - hosts:
        - api.garu.io
      secretName: garu-io-api-cert
