apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yml
- ingress.yml
- deployment.yml
images:
- name: api
  newName: garugaru/garu-io-frontend-api
  newTag: 84079cc0821ab10ec42f08f8215349c9def0bb04
- name: garugaru/garu-io-frontend-api
  newName: garugaru/garu-io-frontend-api
  newTag: 79316a904993a32296fc843717a48cebfa44b63f
