apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yml
- ingress.yml
- deployment.yml
images:
- name: api
  newName: garugaru/garu-io-frontend-api
  newTag: 79316a904993a32296fc843717a48cebfa44b63f
