apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yml
- ingress.yml
- deployment.yml
images:
- name: garugaru/garu-io-frontend-api
  newName: garugaru/garu-io-frontend-api
  newTag: 983f46d515fd072db3d9450ff08e8d2354f5051a
