apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yml
- ingress.yml
- deployment.yml
images:
- name: api
  newName: garugaru/garu-io-frontend-api
  newTag: 79e9adf75b9c8f631426a2643c55b43dc09f9299
- name: garugaru/garu-io-frontend-api
  newName: garugaru/garu-io-frontend-api
  newTag: 79e9adf75b9c8f631426a2643c55b43dc09f9299
